FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./entrypoint.prod.sh .
RUN sed -i 's/\r$//g' /app/entrypoint.prod.sh
RUN chmod +x /app/entrypoint.prod.sh
COPY . .

ENTRYPOINT ["/app/entrypoint.prod.sh"]
